fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gs_person:
    resource: "@GSPersonBundle/Resources/config/routing.yml"
    prefix:   /person

gs_festival:
    resource: "@GSFestivalBundle/Resources/config/routing.yml"
    prefix:   /festival

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
