fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gs_person:
    resource: "@GSPersonBundle/Resources/config/routing.yml"
    prefix:   /person

gs_festival:
    resource: "@GSFestivalBundle/Resources/config/routing.yml"
    prefix:   /festival

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gs_user:
    resource: "@GSUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
